name: Release

on:
  release:
    types: [ released ]

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Set up Java'
        uses: oracle-actions/setup-java@v1
      - name: 'Count modules'
        id: count-modules
        run: echo ::set-output name=size::$(wc --lines < com.github.sormuras.modules/com/github/sormuras/modules/modules.properties)
      - name: 'Build with Bach'
        run: |
          PATH=.bach/bin:$PATH
          bach --project-version ${{ github.event.release.tag_name }} build
      - name: 'Release ${{ github.event.release.tag_name }} with ${{ steps.count-modules.outputs.size }} modules'
        uses: jreleaser/release-action@v1
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: early-access
          arguments: |
            release \
            --auto-config \
            --update \
            --tag-name=${{ github.event.release.tag_name }} \
            --project-name=com.github.sormuras.modules \
            --project-version=${{ github.event.release.tag_name }} \
            --project-version-pattern=java-module \
            --release-name="${{ github.event.release.tag_name }} with ${{ steps.count-modules.outputs.size }} modules" \
            --glob ".bach/workspace/modules/*.jar" \
            --file com.github.sormuras.modules/com/github/sormuras/modules/modules.properties
